### ISSUE TITLE
Not compatible with angular 6.1.8

### ISSUE THREAD

**Issue by komalprana** [ybrodsky/ng-confirmation-modal#2]
Hi @ybrodsky ,

I am using ng-confirmation-modal package into my angular application. I just upgraded angular 5 to angular 6, and it stopped building because of ng-confirmation-modal. I can see on npmjs site, this package has a support of angular-cli latest version and angular core latest version (same version i do have). But still it's giving me below error while building,
 
>  Date: 2018-09-25T14:37:57.358Z
> Hash: 83e00e51985c2efbdfc2
> Time: 11490ms
> chunk {main} main.js, main.js.map (main) 679 bytes [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 689 bytes [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
> chunk {scripts} scripts.js, scripts.js.map (scripts) 1.9 MB  [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 340 kB [initial] [rendered]
> 
> ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
> node_modules/ng-confirmation-modal/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

I want to use this confirmation modal popup in my application. Please correct me if i am doing something wrong.

**Comment by ybrodsky** [comment]
Latest version I tested this and can confirm it works is angular 5.2.0
If you look at the package.json, that's angular's depency.

I think this might be similar to this: https://github.com/angular/angular/issues/21670

Can you have a look in your `node_modules` and check if you have another `node_modules` inside `ng-confirmation-modal`?

**Comment by komalprana** [comment]
Okay, I did see `node_modules` folder inside` ng-confirmation-modal,` I tried deleting node_modules folder and it's building fine again. 

So this means if i have to use this with angular 6.1.8, then i have to remove node_modules folder from ng-confirmation-modal, am i right?

**Comment by ybrodsky** [comment]
Well, that sounds tedious because you would have to remove that folder everytime.
Take a look at this as well:
https://stackoverflow.com/questions/40226639/how-do-i-override-nested-dependencies-with-yarn

You might also do a PR so this supports the latest angular version. If you do so you will probably also have to update ng-bootstrap.

**Comment by komalprana** [comment]
I am not sure what do you mean by stack-overflow link, but i have updated ng-bootstrap version. 

One suggestion, is it possible for you to remove `node_modules ` folder from your npm package? OR may be make this component compatible with angular latest version 6.1.8?

As i did check in all npm packages that i am using for my application, none of them is having node_modules folder in it.

**Comment by actra-gschuster** [comment]
@komalprana It's because ng-confirmation-modal requires an other version of `@angular/core` than your project so yarn installs both, resulting in the conflict.
In your main package.json, add a "resolutions" field that points `@angular/core` to 6.1.8 - this way ng-confirmation-modal will be forced to use this version also, so it won't be installed twice.

See yarn docs for more details: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by ybrodsky** [comment]
@komalprana what @actra-gschuster  is what I meant to say by the link.
I gave you the link because I never did it myself.

I will update the dependencies whenever I get a while and release a new version to go with it.

**Comment by ybrodsky** [comment]
I updated the dependencies. Tested and it seems to work.
Let me know if you have any issue. Install package from npm version 3.0.0

**Comment by komalprana** [comment]
> @komalprana It's because ng-confirmation-modal requires an other version of `@angular/core` than your project so yarn installs both, resulting in the conflict.
> In your main package.json, add a "resolutions" field that points `@angular/core` to 6.1.8 - this way ng-confirmation-modal will be forced to use this version also, so it won't be installed twice.
> 
> See yarn docs for more details: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it

Thanks @actra-gschuster , Good to know.

**Comment by komalprana** [comment]
> @komalprana what @actra-gschuster said is what I meant to say by the link.
> I gave you the link because I never did it myself.
> 
> I will update the dependencies whenever I get a while and release a new version to go with it.

Oops, Sorry. Thanks for updating package. It's working fine now with all angular latest versions and rxjs versions too.
