### ISSUE TITLE
Ng-confirm does not work with angular 7

### ISSUE THREAD

**Issue by play2web** [ybrodsky/ng-confirmation-modal#3]
Current solution does not work with angular 7

**Comment by ybrodsky** [comment]
Feel free to create a PR my friend. Should be easy enough I think.
I am not working with Angular currently.

**Comment by play2web** [comment]
Ok, when i finish PR, you wil merge to master and move version up?

**Comment by ybrodsky** [comment]
Yes, merge and update at npm :+1:

**Comment by play2web** [comment]
Hello, mate, new PR has been created, can you check please, thanks

**Comment by ybrodsky** [comment]
Blindly merged and when I tried to build it for npm some errors pop up. :disappointed: 
I think you will have to update ng-bootstrap as well. Do so and re-create the PR and I will check.

**Comment by play2web** [comment]
Tried ng build --prod, and ng test, all is working ok?
Anything else to try?

**Comment by play2web** [comment]
I think, the problem is not in PR, it is problem when creating NPM package :(

**Comment by ybrodsky** [comment]
May be. Errors poped up when I try running the packgr script. `yarn packagr`

**Comment by play2web** [comment]
The problem is that on some version of npm, templates must be outside of the ts file

**Comment by play2web** [comment]
Have you manage to fix the pack problem?

**Comment by GregTheDev** [comment]
I seem to have got the upgrade working. Not sure what problem you experienced, but after upgrading to Angular 7.2.15 I also updated ng-packagr & installed tsickle (required by updated ng-packagr). 

I've done some very basic testing and everything seems to be working fine so far.

**Comment by ybrodsky** [comment]
If you run `npm run packagr` does it create the build without errors?
If so, create the PR

**Comment by avssolutions** [comment]
https://github.com/avssolutions/angular-confirm-modal

**Comment by GregTheDev** [comment]
I submitted a pull request as well. Looks like we were both working on it at the same time :)

**Comment by ybrodsky** [comment]
Still doesnt build.
```
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbAccordion.html(6,42): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.ɵh.html(3,67): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.ɵh.html(25,67): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbPagination.html(6,11): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbPagination.html(14,11): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbPagination.html(21,67): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbPagination.html(28,11): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbPagination.html(35,11): : An expression of type 'void' cannot be tested for truthiness
node_modules/@ng-bootstrap/ng-bootstrap/ng-bootstrap.d.ts.NgbTabset.html(5,16): : An expression of type 'void' cannot be tested for truthiness
```

I don't know. Honestly I hate Angular way too much to try to fix this crap. Give it a try to @avssolutions package. Will mark this as depracated and link to his.
